-- Charger Installation Inquiry Tracking

CREATE TABLE IF NOT EXISTS charger_installation_inquiry (
    id                          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    inquiry_id                  VARCHAR(50)  NOT NULL,
    customer_name               VARCHAR(150) NOT NULL,
    mobile_no                   VARCHAR(20)  NOT NULL,
    country_code                VARCHAR(10)  NOT NULL DEFAULT '+971',
    email_id                    VARCHAR(150) NOT NULL,
    lead_source                 VARCHAR(50)  NOT NULL,
    assigned_person_name        VARCHAR(150) NOT NULL,
    customer_feedback           TEXT         NULL,
    follow_up_required          ENUM('Yes', 'No') NULL,
    next_follow_up_date         DATE         NULL,
    follow_up_remarks           TEXT         NULL,
    site_visit_required         ENUM('Yes', 'No') NULL,
    site_visit_date             DATE         NULL,
    site_visit_time             VARCHAR(20)  NULL,
    site_visit_location         TEXT         NULL,
    site_visit_person           VARCHAR(150) NULL,
    site_visit_status           VARCHAR(50)  NULL,
    site_visit_remarks          TEXT         NULL,
    cabling_required            ENUM('Yes', 'No') NULL,
    civil_work_required         ENUM('Yes', 'No') NULL,
    existing_electrical_setup   TEXT         NULL,
    charger_availability        VARCHAR(50)  NULL,
    charger_capacity            VARCHAR(100) NULL,
    charger_cost                DECIMAL(10, 2) NULL,
    material_requirement_details TEXT        NULL,
    material_cost_to_us         DECIMAL(10, 2) NULL,
    material_cost_quoted        DECIMAL(10, 2) NULL,
    installation_date           DATE         NULL,
    installation_person         VARCHAR(150) NULL,
    installation_completion_date DATE        NULL,
    installation_completed_by   VARCHAR(150) NULL,
    final_amount                DECIMAL(10, 2) NULL,
    completion_certificate      VARCHAR(255) NULL,
    charger_purchase_invoice    VARCHAR(255) NULL,
    -- enquiry_status shorthand: ASG=Assigned, CTC=Contacted, FUR=Follow-up Required,
    -- SVP=Site Visit Planned, SVC=Site Visit Completed, QSH=Quotation Shared,
    -- ISC=Installation Scheduled, INC=Installation Completed, LCN=Lost / Cancelled
    enquiry_status              ENUM('ASG', 'CTC', 'FUR', 'SVP', 'SVC', 'QSH', 'ISC', 'INC', 'LCN') NOT NULL,
    lost_cancelled_remark       TEXT         NULL,
    created_at                  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_charger_installation_inquiry_id (inquiry_id),
    KEY idx_charger_installation_inquiry_mobile (mobile_no),
    KEY idx_charger_installation_inquiry_lead_source (lead_source),
    KEY idx_charger_installation_inquiry_enquiry_status (enquiry_status),
    KEY idx_charger_installation_inquiry_site_visit_status (site_visit_status),
    KEY idx_charger_installation_inquiry_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
